version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cufarm
      MYSQL_DATABASE: cufarm
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/cufarm/cufarmm.sql:/cufarm.sql